<a href="https://colab.research.google.com/github/cindy-purity/Numpy/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array Creation**

In [ ]:
#Create a numpy array of size 10, filled with zeros.
import numpy as np
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#Create a numpy array with values ranging from 10 to 49.
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#Create a numpy matrix of 2*2 integers, filled with ones.
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

In [ ]:
#Create a numpy matrix of 3*2 float numbers, filled with ones.
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
x = np.arange(4, dtype=int)
np.ones_like(x)

array([1, 1, 1, 1])

In [ ]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
x = np.array([[1,2,3], [4,5,6]], dtype=int)
np.zeros_like(x)


array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#Create a numpy matrix of 4*4 integers, filled with fives.
np.ones([4,4], dtype = int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
x = np.array([[2,3],[6,2]], dtype=int)
np.ones_like(x) * 7

array([[7, 7],
       [7, 7]])

In [ ]:
#Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Create a numpy array, filled with 3 random integer values between 1 and 10.
np.random.randint(10, size=3)

array([4, 8, 3])

In [ ]:
#Create a 3*3*3 numpy matrix, filled with random float values.
np.random.randn(3,3,3)

array([[[ 1.10415809,  0.17489744,  0.52044652],
        [ 0.49815687,  0.09645821,  1.03673205],
        [ 0.94274593,  0.85417247,  0.3394283 ]],

       [[ 0.05339318,  1.40789786, -0.69937141],
        [ 0.14155853,  2.4878818 , -1.22903298],
        [-0.87995204,  0.42477485, -2.05130113]],

       [[-0.40390927,  0.66979625,  1.12595438],
        [-0.44492907,  0.56573585, -1.02832406],
        [-1.99424231, -0.06234122, -1.28919467]]])

In [ ]:
#Given the X python list convert it to an Y numpy array
x = [1,2,3]
print(x, type(x))
y = np.array(x)
print(y, type(y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [ ]:
#Create a numpy array with the odd numbers between 1 to 10.
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
#Create a 3*3 numpy matrix, filled with values ranging from 0 to 8.
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Array Indexation**

In [ ]:
#Given the X numpy array, show it's first element
x = np.array(['A','B','C','D,','E'])
x[0]

'A'

In [ ]:
#Given the X numpy array, show it's last element
x[-1]

'E'

In [ ]:
#Given the X numpy array, show all middle elements
x[1:-1]

array(['B', 'C', 'D,'], dtype='<U2')

In [ ]:
#Given the X numpy array, show the elements in reverse position
x[::-1]

array(['E', 'D,', 'C', 'B', 'A'], dtype='<U2')

In [ ]:
#Given the X numpy array, show the elements in an odd position
x[::2]

array(['A', 'C', 'E'], dtype='<U2')

In [ ]:
#Given the X numpy matrix, show the first row elements
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

In [ ]:
#Given the X numpy matrix, show the first element on first row.
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0, 0]

1

In [ ]:
#Given the X numpy matrix, show the last element on last row
X[-1, -1]

16

In [ ]:
#Given the X numpy matrix, show the middle row elements
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [ ]:
#Given the X numpy matrix, show the first two elements on the first two rows
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [ ]:
#Given the X numpy matrix, show the last two elements on the last two rows
X[2:, 2:]

array([[11, 12],
       [15, 16]])

**Array Manipulation**

In [ ]:
#Convert the given integer numpy array to float
X = [-5, -3, 0, 10, 40]

np.array(X, float)

array([-5., -3.,  0., 10., 40.])

In [ ]:
#Reverse the given numpy array (first element becomes last)
X[::-1]

In [ ]:
#Order (sort) the given numpy array
X = [0, 10, -5, 40, -3]

X.sort()
X


[-5, -3, 0, 10, 40]

In [ ]:
#Given the X numpy array, set the fifth element equal to 1
X[4] = 1
X

[-5, -3, 0, 10, 1]

In [ ]:
#Given the X numpy array, change the 50 with a 40
X = np.array([10, 20, 30, 50])

X[3] = 4
X

array([10, 20, 30,  4])

In [ ]:
#Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [ ]:
#Given the X numpy matrix, change the last item on the last row with a 0
X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  0]])

In [ ]:
#Given the X numpy matrix, add 5 to every element
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

**Boolean arrays (also called masks)**

In [ ]:
#Given the X numpy array, make a mask showing negative elements
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [ ]:
#Given the X numpy array, get the negative elements
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [ ]:
#Given the X numpy array, get numbers higher than 5
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]


array([ 6, 10])

In [ ]:
#Given the X numpy array, get numbers higher than the elements mean
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [ ]:
#Given the X numpy array, get numbers equal to 2 or 10
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

**Logic Functions**

In [ ]:
#Given the X numpy array, return True if none of its elements is zero
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

In [ ]:
#Given the X numpy array, return True if any of its elements is zero
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

**Summary statistics**

In [ ]:
#Given the X numpy array, show the sum of its elements
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

X.sum()

43

In [ ]:
#Given the X numpy array, show the mean value of its elements
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.mean()


3.7

In [ ]:
#Given the X numpy matrix, show the sum of its columns
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)   #axis=0 is column, #axis=1 is row

array([28, 32, 36, 40])

In [ ]:
#Given the X numpy matrix, show the mean value of its rows
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=1)

array([10, 26, 42, 58])

In [ ]:
#Given the X numpy array, show the max value of its elements
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.max()

10